"""Initial migration

Revision ID: c6cfb87d7ecb
Revises: 
Create Date: 2025-11-21 18:08:07.432224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cfb87d7ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_urls_short_code', 'urls', ['short_code'], unique=False)
    op.create_table('url_visits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.BigInteger(), nullable=False),
    sa.Column('visitor_ip', sa.String(length=45), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_visits_url_id'), 'url_visits', ['url_id'], unique=False)
    op.create_index('ix_url_visits_url_id_visited_at', 'url_visits', ['url_id', 'visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_visits_url_id_visited_at', table_name='url_visits')
    op.drop_index(op.f('ix_url_visits_url_id'), table_name='url_visits')
    op.drop_table('url_visits')
    op.drop_index('ix_urls_short_code', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###